# create actions for building nodejs app
name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        working-directory: ./completesolution
        run: npm install
      - name: Build
        working-directory: ./completesolution
        run: npm run build --if-present
      - name: Test
        working-directory: ./completesolution
        run: npm run start && npm run test